"use client";
import { useCallback, useEffect, useState } from "react";
import { errorMessage, readApiResponse } from "@curais/ui";

export function FamilyManager() {
  const [links, setLinks] = useState([]); const [message, setMessage] = useState("Loading family…");
  const load = useCallback(async () => { const response = await fetch("/api/curais/family", { cache: "no-store" }); const data = await readApiResponse(response); setLinks(data.family || []); setMessage(""); }, []);
  useEffect(() => { load().catch((error) => setMessage(errorMessage(error, "Unable to load family connections."))); }, [load]);
  async function invite(event) { event.preventDefault(); const form = event.currentTarget; setMessage("Sending invitation…"); try { const response = await fetch("/api/curais/family", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(form))) }); await readApiResponse(response); form.reset(); await load(); } catch (error) { setMessage(errorMessage(error, "Unable to send the invitation.")); } }
  async function respond(id, accept, shareFamilyHistory = false) { try { const response = await fetch(`/api/curais/family/${encodeURIComponent(id)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ accept, shareFamilyHistory }) }); await readApiResponse(response); await load(); } catch (error) { setMessage(errorMessage(error, "Unable to update the invitation.")); } }
  return <div className="mt-8 grid gap-6 md:grid-cols-[.8fr_1.2fr]"><form onSubmit={invite} className="glass-strong h-fit rounded-[2rem] p-5"><h2 className="font-quicksand text-xl font-bold">Connect a family member</h2><p className="mt-2 text-sm text-aid-muted">They need their own patient account and must accept.</p><label className="mt-4 block text-sm font-bold">Their account email<input required name="email" type="email" className="mt-1.5 w-full rounded-xl bg-white/60 px-3 py-3" /></label><label className="mt-4 block text-sm font-bold">Relationship<select name="relationship" className="mt-1.5 w-full rounded-xl bg-white/60 px-3 py-3"><option>Parent</option><option>Child</option><option>Sibling</option><option>Spouse</option><option>Grandparent</option><option>Other</option></select></label><button className="mt-5 w-full rounded-xl bg-aid-teal px-4 py-3 font-bold text-white">Send invitation</button><p className="mt-3 text-sm text-aid-muted">{message}</p></form><div className="space-y-3">{links.map((link) => <article key={link.id} className="glass-strong rounded-2xl p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-quicksand text-lg font-bold">{link.otherDisplayName}</h3><p className="text-sm text-aid-muted">{link.relationship} · {link.status}</p></div>{link.direction === "incoming" && link.status === "pending" ? <div className="flex gap-2"><button onClick={() => respond(link.id, false)} className="rounded-xl bg-white/60 px-3 py-2 text-sm font-bold">Decline</button><button onClick={() => respond(link.id, true, true)} className="rounded-xl bg-aid-teal px-3 py-2 text-sm font-bold text-white">Accept + share history</button></div> : null}</div>{link.status === "active" ? <p className="mt-3 rounded-xl bg-aid-teal/10 px-3 py-2 text-xs font-semibold text-aid-teal">{link.shareFamilyHistory ? "Family-history context sharing enabled" : "Connected without history sharing"}</p> : null}</article>)}{links.length === 0 ? <div className="glass-strong rounded-2xl p-6 text-aid-muted">No family connections yet.</div> : null}</div></div>;
}
