"use client";
import { useCallback, useEffect, useState } from "react";
import { errorMessage, readApiResponse, useToast } from "@curais/ui";

export function ClinicalHistory({ patientID }) {
  const { showToast } = useToast();
  const [items, setItems] = useState([]); const [message, setMessage] = useState("Loading longitudinal record…");
  const endpoint = `/api/curais/patients/${encodeURIComponent(patientID)}/history`;
  const load = useCallback(async () => { const response = await fetch(endpoint, { cache: "no-store" }); const data = await readApiResponse(response); setItems(data.history || []); setMessage(""); }, [endpoint]);
  useEffect(() => { load().catch((error) => { setMessage(""); showToast({ type: "error", title: "Clinical history unavailable", message: errorMessage(error, "Unable to load history.") }); }); }, [load, showToast]);
  async function add(event) { event.preventDefault(); const form = event.currentTarget; setMessage("Saving attributable note…"); try { const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(form))) }); await readApiResponse(response); form.reset(); await load(); showToast({ type: "success", title: "Clinical note saved", message: "The attributable history entry is now part of the patient record." }); } catch (error) { setMessage(""); showToast({ type: "error", title: "Clinical note was not saved", message: errorMessage(error, "Could not save note.") }); } }
  return <section className="mt-8"><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-aid-teal">Longitudinal record</p><h2 className="mt-1 font-quicksand text-2xl font-bold">Clinical history</h2></div><p className="text-sm text-aid-muted">{message}</p></div><div className="mt-4 grid gap-5 md:grid-cols-[.75fr_1.25fr]"><form onSubmit={add} className="glass-strong h-fit rounded-2xl p-5"><h3 className="font-bold">Add clinical note</h3><input required name="title" placeholder="Diagnosis or visit title" className="mt-4 w-full rounded-xl bg-white/60 px-3 py-3" /><select name="category" className="mt-3 w-full rounded-xl bg-white/60 px-3 py-3"><option value="visit">Visit</option><option value="diagnosis">Diagnosis</option><option value="procedure">Procedure</option><option value="condition">Condition</option><option value="family_history">Family history</option><option value="other">Other</option></select><input name="occurredAt" type="date" className="mt-3 w-full rounded-xl bg-white/60 px-3 py-3" /><textarea name="details" placeholder="Clinical details" className="mt-3 min-h-28 w-full rounded-xl bg-white/60 px-3 py-3" /><button className="mt-4 w-full rounded-xl bg-aid-teal px-4 py-3 font-bold text-white">Save note</button></form><div className="space-y-3">{items.map((item) => <article key={item.id} className="glass-strong rounded-2xl p-5"><div className="flex justify-between gap-3"><h3 className="font-quicksand text-lg font-bold">{item.title}</h3><span className="text-xs font-bold uppercase text-aid-teal">{item.category.replace("_", " ")}</span></div><p className="mt-2 text-sm text-aid-muted">{item.details || "No details"}</p><p className="mt-3 text-xs text-aid-muted">{item.occurredAt || item.createdAt.slice(0, 10)} · {item.source}</p></article>)}{!items.length ? <div className="glass rounded-2xl p-5 text-sm text-aid-muted">No recorded history.</div> : null}</div></div></section>;
}
