"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Loader2, Plus } from "lucide-react";
import { errorMessage, readApiResponse } from "@curais/ui";

const configs = {
  appointments: { title: "Appointments", singular: "appointment", fields: [{name:"scheduledAt",label:"Date and time",type:"datetime-local",required:true},{name:"durationMinutes",label:"Duration (minutes)",type:"number",defaultValue:"30",required:true},{name:"reason",label:"Reason",required:true}], summary: i=>`${formatDate(i.scheduledAt)} · ${i.durationMinutes} min · ${i.status}` },
  encounters: { title: "Encounters", singular: "encounter", fields: [{name:"chiefComplaint",label:"Chief complaint",required:true},{name:"bloodPressure",label:"Blood pressure",placeholder:"120/80"},{name:"pulseBpm",label:"Pulse BPM",type:"number"},{name:"temperatureC",label:"Temperature °C",type:"number",step:"0.1"},{name:"spo2Percent",label:"SpO₂ %",type:"number"},{name:"subjective",label:"Subjective",area:true},{name:"objective",label:"Objective",area:true},{name:"assessment",label:"Assessment",area:true},{name:"plan",label:"Plan",area:true},{name:"status",label:"Record status",select:["draft","signed"]}], summary:i=>`${formatDate(i.createdAt)} · ${i.status}` },
  prescriptions: { title:"Prescriptions",singular:"prescription",fields:[{name:"medication",label:"Medication",required:true},{name:"dosage",label:"Dosage",required:true},{name:"frequency",label:"Frequency",required:true},{name:"duration",label:"Duration"},{name:"instructions",label:"Instructions",area:true}],summary:i=>`${i.dosage} · ${i.frequency} · ${i.status}`},
  labs: { title:"Lab orders",singular:"lab order",fields:[{name:"testName",label:"Test name",required:true},{name:"priority",label:"Priority",select:["routine","urgent"]}],summary:i=>`${i.priority} · ${i.status} · ${formatDate(i.orderedAt)}`},
};

export function EMRWorkspace({ resource }) {
  const config=configs[resource]; const [patients,setPatients]=useState([]); const [items,setItems]=useState([]); const [message,setMessage]=useState("Loading…"); const listKey=resource;
  const endpoint=`/api/curais/emr/${resource}`;
  const load=useCallback(async()=>{const [recordsResponse,patientsResponse]=await Promise.all([fetch(endpoint,{cache:"no-store"}),fetch("/api/curais/patients",{cache:"no-store"})]);const [records,people]=await Promise.all([readApiResponse(recordsResponse),readApiResponse(patientsResponse)]);setItems(records[listKey]||[]);setPatients(people.patients||[]);setMessage("");},[endpoint,listKey]);
  useEffect(()=>{load().catch(e=>setMessage(errorMessage(e,"Unable to load records.")));},[load]);
  async function create(event){event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));for(const field of config.fields){if(field.type==="number"&&values[field.name])values[field.name]=Number(values[field.name]);}setMessage("Saving…");try{const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});await readApiResponse(response);form.reset();await load();}catch(error){setMessage(errorMessage(error,"Unable to save the clinical record."));}}
  const sorted=useMemo(()=>items,[items]);
  return <div className="mt-7 grid gap-6 lg:grid-cols-[.72fr_1.28fr]"><form onSubmit={create} className="glass-strong h-fit rounded-[2rem] p-5"><h2 className="inline-flex items-center gap-2 font-quicksand text-xl font-bold"><Plus className="h-5 w-5 text-aid-teal" />New {config.singular}</h2><label className="mt-5 block text-sm font-bold">Patient<select required name="patientId" className={inputClass}><option value="">Select a consented patient</option>{patients.map(p=><option key={p.patientId} value={p.patientId}>{p.displayName}</option>)}</select></label>{config.fields.map(field=><Field key={field.name} field={field}/>) }<button disabled={!patients.length} className="mt-5 w-full rounded-xl bg-aid-teal px-4 py-3 font-bold text-white disabled:opacity-50">Save {config.singular}</button>{!patients.length?<p className="mt-3 text-xs text-aid-muted">A patient must share their profile with your clinic first.</p>:null}</form><section><p role="status" className="inline-flex items-center gap-2 text-sm text-aid-muted">{message?<Loader2 className="h-4 w-4 animate-spin"/>:null}{message||`${items.length} record${items.length===1?"":"s"}`}</p><div className="mt-4 space-y-3">{sorted.map(item=><article key={item.id} className="glass-strong rounded-2xl p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-aid-teal">{item.patientName}</p><h3 className="mt-1 font-quicksand text-lg font-bold">{item.reason||item.chiefComplaint||item.medication||item.testName}</h3></div><p className="text-sm font-semibold text-aid-muted">{config.summary(item)}</p></div>{item.assessment?<p className="mt-3 text-sm text-aid-muted"><strong>Assessment:</strong> {item.assessment}</p>:null}{item.plan?<p className="mt-2 text-sm text-aid-muted"><strong>Plan:</strong> {item.plan}</p>:null}{item.instructions?<p className="mt-2 text-sm text-aid-muted">{item.instructions}</p>:null}</article>)}{!message&&!items.length?<div className="glass rounded-2xl p-6 text-aid-muted">No {config.title.toLowerCase()} yet.</div>:null}</div></section></div>;
}
const inputClass="mt-1.5 w-full rounded-xl border border-white/70 bg-white/60 px-3 py-3 font-normal outline-none focus:border-aid-teal";
function Field({field}){return <label className="mt-4 block text-sm font-bold">{field.label}{field.area?<textarea name={field.name} required={field.required} placeholder={field.placeholder} className={`${inputClass} min-h-20`}/>:field.select?<select name={field.name} className={inputClass}>{field.select.map(v=><option key={v}>{v}</option>)}</select>:<input name={field.name} type={field.type||"text"} step={field.step} required={field.required} placeholder={field.placeholder} defaultValue={field.defaultValue} className={inputClass}/>}</label>}
function formatDate(value){if(!value)return "";const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleString();}
