"use client";

import { useEffect, useRef, useState } from "react";
import { motion } from "framer-motion";
import { Activity, ArrowRight, Building2, HeartPulse, Phone, ShieldCheck, UserRound, X } from "lucide-react";
import { useToast } from "@curais/ui";

export function StartModal({ type, onClose, patientURL, doctorURL }) {
  const panelRef = useRef(null);
  useEffect(() => {
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    const keydown = (event) => {
      if (event.key === "Escape") onClose();
      if (event.key === "Tab") trapFocus(event, panelRef.current);
    };
    document.addEventListener("keydown", keydown);
    panelRef.current?.querySelector("button, a, input")?.focus();
    return () => { document.body.style.overflow = previousOverflow; document.removeEventListener("keydown", keydown); };
  }, [onClose]);

  return <motion.div className="fixed inset-0 z-[90] flex items-end justify-center bg-aid-ink/35 p-3 backdrop-blur-md sm:items-center sm:p-6" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose()}}><motion.section ref={panelRef} role="dialog" aria-modal="true" aria-labelledby="modal-title" initial={{opacity:0,y:30,scale:.97}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:20,scale:.98}} transition={{duration:.25,ease:[.22,1,.36,1]}} className="glass-strong relative max-h-[calc(100dvh-1.5rem)] w-full max-w-2xl overflow-y-auto rounded-[2rem] p-5 sm:p-7"><button onClick={onClose} className="absolute right-4 top-4 inline-flex h-11 w-11 items-center justify-center rounded-xl bg-white/55 text-aid-muted" aria-label="Close dialog"><X className="h-5 w-5"/></button>{type==="demo"?<DemoForm/>:type==="immediate"?<ImmediateCare patientURL={patientURL}/>:<ChooseApp patientURL={patientURL} doctorURL={doctorURL}/>}</motion.section></motion.div>;
}

function ChooseApp({patientURL,doctorURL}){return <div><p className="eyebrow">Choose your space</p><h2 id="modal-title" className="mt-2 pr-12 font-quicksand text-3xl font-bold">How would you like to use Curais?</h2><p className="mt-3 max-w-xl leading-7 text-aid-muted">Patient and clinical experiences stay separate so every screen is focused and every permission is clear.</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><AppChoice href={`${patientURL}/signin`} icon={UserRound} title="Patient app" text="Immediate Care, My Health, family context and sharing controls." action="Open patient app"/><AppChoice href={`${doctorURL}/signin`} icon={Building2} title="Doctor EMR" text="Consented patients, appointments, encounters, medicines and labs." action="Open doctor workspace"/></div><p className="mt-5 flex items-start gap-2 text-xs leading-5 text-aid-muted"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-aid-teal"/>Each app has its own secure sign-in. Health records are never available from this public website.</p></div>}
function AppChoice({href,icon:Icon,title,text,action}){return <a href={href} className="glass group rounded-2xl p-5 transition hover:-translate-y-1 hover:bg-white/60"><span className="inline-flex h-11 w-11 items-center justify-center rounded-xl bg-aid-teal/10 text-aid-teal"><Icon className="h-5 w-5"/></span><h3 className="mt-5 font-quicksand text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-aid-muted">{text}</p><p className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-aid-teal">{action}<ArrowRight className="h-4 w-4"/></p></a>}

function ImmediateCare({patientURL}){const options=["Heart pain","Breathing trouble","Bleeding","Burn or bite"];return <div><p className="eyebrow">Curais Immediate Care</p><h2 id="modal-title" className="mt-2 pr-12 font-quicksand text-3xl font-bold">Need a clear next step?</h2><p className="mt-3 leading-7 text-aid-muted">Continue to SnapAid for general first-aid guidance—no login required. If someone may be in immediate danger, call emergency services now.</p><a href="tel:112" className="mt-6 flex min-h-14 items-center justify-center gap-3 rounded-2xl bg-aid-emergency px-5 py-3 font-extrabold text-white shadow-[0_15px_35px_rgba(180,35,24,.2)]"><Phone className="h-5 w-5"/>Call emergency services — 112</a><div className="mt-6"><p className="text-xs font-extrabold uppercase tracking-[.14em] text-aid-teal">Common concerns</p><div className="mt-3 grid grid-cols-2 gap-2">{options.map(item=><a key={item} href={`${patientURL}/immediate-care`} className="glass flex min-h-12 items-center gap-2 rounded-xl px-3 py-3 text-sm font-bold"><Activity className="h-4 w-4 text-aid-teal"/>{item}</a>)}</div></div><a href={`${patientURL}/immediate-care`} className="button-primary mt-6 w-full"><HeartPulse className="h-5 w-5"/>Open Immediate Care</a><p className="mt-4 text-center text-xs leading-5 text-aid-muted">Curais provides general guidance, not a diagnosis or substitute for professional care.</p></div>}

function DemoForm(){const{showToast}=useToast();const[errors,setErrors]=useState({});function submit(event){event.preventDefault();const form=event.currentTarget;const data=Object.fromEntries(new FormData(form));const next={};if(!String(data.name||"").trim())next.name="Enter your name.";if(!/^\S+@\S+\.\S+$/.test(String(data.email||"")))next.email="Enter a valid work email.";if(!String(data.organization||"").trim())next.organization="Enter your clinic or hospital name.";if(Object.keys(next).length){setErrors(next);form.elements.namedItem(Object.keys(next)[0])?.focus();return}const subject=encodeURIComponent(`Curais clinic walkthrough — ${data.organization}`);const body=encodeURIComponent(`Name: ${data.name}\nEmail: ${data.email}\nOrganization: ${data.organization}\nTeam size: ${data.teamSize}\n\nI would like a Curais clinic walkthrough.`);showToast({type:"info",title:"Opening your email app",message:"Review the pre-filled request, then send it when you are ready."});window.location.href=`mailto:hello@curais.com?subject=${subject}&body=${body}`;}return <div><p className="eyebrow">Clinic walkthrough</p><h2 id="modal-title" className="mt-2 pr-12 font-quicksand text-3xl font-bold">See Curais with your workflow in mind.</h2><p className="mt-3 leading-7 text-aid-muted">Tell us who you are. Submitting opens your email app with a pre-filled request; this website does not store the form.</p><form onSubmit={submit} noValidate className="mt-6 grid gap-4 sm:grid-cols-2"><ModalField label="Your name" name="name" error={errors.name} clear={()=>setErrors(v=>({...v,name:""}))}/><ModalField label="Work email" name="email" type="email" error={errors.email} clear={()=>setErrors(v=>({...v,email:""}))}/><ModalField label="Clinic or hospital" name="organization" error={errors.organization} clear={()=>setErrors(v=>({...v,organization:""}))}/><label className="text-sm font-bold">Team size<select name="teamSize" className="mt-1.5 w-full rounded-xl border border-white/70 bg-white/55 px-3 py-3 font-normal outline-none focus:border-aid-teal"><option>1–5</option><option>6–20</option><option>21–50</option><option>51+</option></select></label><button className="button-primary sm:col-span-2">Prepare email request <ArrowRight className="h-4 w-4"/></button></form></div>}
function ModalField({label,name,type="text",error,clear}){const id=`demo-${name}`;return <label htmlFor={id} className="text-sm font-bold">{label}<input id={id} name={name} type={type} onChange={clear} aria-invalid={Boolean(error)} aria-describedby={error?`${id}-error`:undefined} className={`mt-1.5 w-full rounded-xl border bg-white/55 px-3 py-3 font-normal outline-none focus:ring-2 ${error?"border-aid-emergency/50 focus:ring-red-100":"border-white/70 focus:border-aid-teal focus:ring-aid-teal/15"}`}/>{error?<span id={`${id}-error`} className="mt-1 block text-xs font-semibold text-aid-emergency">{error}</span>:null}</label>}

function trapFocus(event,panel){if(!panel)return;const nodes=[...panel.querySelectorAll('a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled])')];if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}
